version: '3.8'

services:
  db:
    image: postgres:12
    container_name: postgres_matronin
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_matronin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: matronin_admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db